-- MySQL Script generated by MySQL Workbench
-- Tue Jan 14 12:48:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cul_dAmpolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cul_dAmpolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cul_dAmpolla` DEFAULT CHARACTER SET utf8 ;
USE `Cul_dAmpolla` ;

-- -----------------------------------------------------
-- Table `Cul_dAmpolla`.`tProveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_dAmpolla`.`tProveidor` (
  `nif` VARCHAR(9) NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`nif`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_dAmpolla`.`tMarca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_dAmpolla`.`tMarca` (
  `idMarca` INT NOT NULL,
  `tProveidor_nif` INT NOT NULL,
  PRIMARY KEY (`idMarca`),
  UNIQUE INDEX `idMarca_UNIQUE` (`idMarca` ASC) VISIBLE,
  INDEX `fk_tMarca_tProveidor_idx` (`tProveidor_nif` ASC) VISIBLE,
  CONSTRAINT `fk_tMarca_tProveidor`
    FOREIGN KEY (`tProveidor_nif`)
    REFERENCES `Cul_dAmpolla`.`tProveidor` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_dAmpolla`.`tGraduacio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_dAmpolla`.`tGraduacio` (
  `idGraduacio` INT NOT NULL AUTO_INCREMENT,
  `graduacio_right` FLOAT(4,2) NULL,
  `graduacio_left` FLOAT(4,2) NULL,
  PRIMARY KEY (`idGraduacio`),
  UNIQUE INDEX `idGraduacio_UNIQUE` (`idGraduacio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_dAmpolla`.`tUlleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_dAmpolla`.`tUlleres` (
  `idUlleres` INT NOT NULL,
  `preu` INT NOT NULL,
  `color_montura` VARCHAR(255) NULL,
  `color_vidre` VARCHAR(255) NULL,
  `tipus_montura` ENUM('flotant', 'pasta', 'metàl·lica') NULL,
  `tGraduacio_idGraduacio` INT NOT NULL,
  PRIMARY KEY (`idUlleres`),
  UNIQUE INDEX `idUlleres_UNIQUE` (`idUlleres` ASC) VISIBLE,
  INDEX `fk_tUlleres_tGraduacio1_idx` (`tGraduacio_idGraduacio` ASC) VISIBLE,
  CONSTRAINT `fk_tUlleres_tGraduacio1`
    FOREIGN KEY (`tGraduacio_idGraduacio`)
    REFERENCES `Cul_dAmpolla`.`tGraduacio` (`idGraduacio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_dAmpolla`.`tPais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_dAmpolla`.`tPais` (
  `idtPais` INT NOT NULL AUTO_INCREMENT,
  `Pais` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idtPais`),
  UNIQUE INDEX `idtPais_UNIQUE` (`idtPais` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_dAmpolla`.`tProveidorAdress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_dAmpolla`.`tProveidorAdress` (
  `idProveidorAdress` INT NOT NULL,
  `tProveidor_nif` INT NOT NULL,
  `carrer` VARCHAR(255) NOT NULL,
  `numero` INT NOT NULL,
  `pis` VARCHAR(255) NULL,
  `porta` VARCHAR(255) NULL,
  `ciutat` VARCHAR(255) NULL,
  `codi postal` VARCHAR(255) NULL,
  `tPais_idtPais` INT NOT NULL,
  PRIMARY KEY (`idProveidorAdress`),
  UNIQUE INDEX `nif_UNIQUE` (`idProveidorAdress` ASC) VISIBLE,
  INDEX `fk_tProveidorAdress_tProveidor1_idx` (`tProveidor_nif` ASC) VISIBLE,
  INDEX `fk_tProveidorAdress_tPais1_idx` (`tPais_idtPais` ASC) VISIBLE,
  CONSTRAINT `fk_tProveidorAdress_tProveidor1`
    FOREIGN KEY (`tProveidor_nif`)
    REFERENCES `Cul_dAmpolla`.`tProveidor` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tProveidorAdress_tPais1`
    FOREIGN KEY (`tPais_idtPais`)
    REFERENCES `Cul_dAmpolla`.`tPais` (`idtPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_dAmpolla`.`tClient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_dAmpolla`.`tClient` (
  `mail` VARCHAR(255) NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `adress` VARCHAR(255) NOT NULL,
  `telephon` VARCHAR(45) NOT NULL,
  `data_registre` DATETIME NOT NULL,
  `id_ClientRecomenatMail` VARCHAR(255) NULL,
  `tClient_mail` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`mail`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE,
  INDEX `fk_tClient_tClient1_idx` (`tClient_mail` ASC) VISIBLE,
  CONSTRAINT `fk_tClient_tClient1`
    FOREIGN KEY (`tClient_mail`)
    REFERENCES `Cul_dAmpolla`.`tClient` (`mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_dAmpolla`.`tEmpleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_dAmpolla`.`tEmpleat` (
  `idEmpleat` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEmpleat`),
  UNIQUE INDEX `nif_UNIQUE` (`idEmpleat` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_dAmpolla`.`tUlleres_has_tMarca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_dAmpolla`.`tUlleres_has_tMarca` (
  `tUlleres_idUlleres` INT NOT NULL,
  `tMarca_idMarca` INT NOT NULL,
  PRIMARY KEY (`tUlleres_idUlleres`, `tMarca_idMarca`),
  INDEX `fk_tUlleres_has_tMarca_tMarca1_idx` (`tMarca_idMarca` ASC) VISIBLE,
  INDEX `fk_tUlleres_has_tMarca_tUlleres1_idx` (`tUlleres_idUlleres` ASC) VISIBLE,
  CONSTRAINT `fk_tUlleres_has_tMarca_tUlleres1`
    FOREIGN KEY (`tUlleres_idUlleres`)
    REFERENCES `Cul_dAmpolla`.`tUlleres` (`idUlleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tUlleres_has_tMarca_tMarca1`
    FOREIGN KEY (`tMarca_idMarca`)
    REFERENCES `Cul_dAmpolla`.`tMarca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_dAmpolla`.`tClient_has_tUlleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_dAmpolla`.`tClient_has_tUlleres` (
  `tClient_mail` VARCHAR(255) NOT NULL,
  `tUlleres_idUlleres` INT NOT NULL,
  PRIMARY KEY (`tClient_mail`, `tUlleres_idUlleres`),
  INDEX `fk_tClient_has_tUlleres_tUlleres1_idx` (`tUlleres_idUlleres` ASC) VISIBLE,
  INDEX `fk_tClient_has_tUlleres_tClient1_idx` (`tClient_mail` ASC) VISIBLE,
  CONSTRAINT `fk_tClient_has_tUlleres_tClient1`
    FOREIGN KEY (`tClient_mail`)
    REFERENCES `Cul_dAmpolla`.`tClient` (`mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tClient_has_tUlleres_tUlleres1`
    FOREIGN KEY (`tUlleres_idUlleres`)
    REFERENCES `Cul_dAmpolla`.`tUlleres` (`idUlleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_dAmpolla`.`tUlleres_has_tEmpleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_dAmpolla`.`tUlleres_has_tEmpleat` (
  `tUlleres_idUlleres` INT NOT NULL,
  `tEmpleat_nif` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`tUlleres_idUlleres`, `tEmpleat_nif`),
  INDEX `fk_tUlleres_has_tEmpleat_tEmpleat1_idx` (`tEmpleat_nif` ASC) VISIBLE,
  INDEX `fk_tUlleres_has_tEmpleat_tUlleres1_idx` (`tUlleres_idUlleres` ASC) VISIBLE,
  CONSTRAINT `fk_tUlleres_has_tEmpleat_tUlleres1`
    FOREIGN KEY (`tUlleres_idUlleres`)
    REFERENCES `Cul_dAmpolla`.`tUlleres` (`idUlleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tUlleres_has_tEmpleat_tEmpleat1`
    FOREIGN KEY (`tEmpleat_nif`)
    REFERENCES `Cul_dAmpolla`.`tEmpleat` (`idEmpleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_dAmpolla`.`tProveidorTelefon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_dAmpolla`.`tProveidorTelefon` (
  `idProveidorTelefon` INT NOT NULL,
  `fax` VARCHAR(45) NOT NULL,
  `tProveidor_nif` VARCHAR(9) NOT NULL,
  `telefon` INT NULL,
  PRIMARY KEY (`idProveidorTelefon`),
  INDEX `fk_tTelefon_tProveidor1_idx` (`tProveidor_nif` ASC) VISIBLE,
  CONSTRAINT `fk_tTelefon_tProveidor1`
    FOREIGN KEY (`tProveidor_nif`)
    REFERENCES `Cul_dAmpolla`.`tProveidor` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_dAmpolla`.`tClientTelephon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_dAmpolla`.`tClientTelephon` (
  `idClientTelephon` INT NOT NULL,
  `Telefono` INT NULL,
  `tClient_mail` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idClientTelephon`),
  INDEX `fk_tClientTelephon_tClient1_idx` (`tClient_mail` ASC) VISIBLE,
  CONSTRAINT `fk_tClientTelephon_tClient1`
    FOREIGN KEY (`tClient_mail`)
    REFERENCES `Cul_dAmpolla`.`tClient` (`mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
